version: '3'

services:
  postgres:
    build: ./db/postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./db/data/postgres:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./db/data/redis/redis.conf:/usr/local/etc/redis/redis.conf
  link:
    build: ./
    restart: always
    ports:
      - '8080:8080'
